apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-test
rules:
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - endpoints
      - services
      - pods
      - namespaces
      - machines
      