apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-default
  namespace: dns-test
data:
  Corefile: |
    .:5353 {
        debug
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          machines verified
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        proxy . /etc/resolv.conf
        cache 30
        reload
    }

