apiVersion: v1
kind: Service
metadata:
  name: dns-default
  namespace: dns-test
spec:
  ports:
    - name: dns
      protocol: UDP
      port: 53535
      targetPort: dns
    - name: dns-tcp
      protocol: TCP
      port: 53535
      targetPort: dns-tcp
  selector:
      app: coredns-test
